# Generated by Django 4.2.4 on 2023-10-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('foto', models.ImageField(upload_to='imagens/')),
                ('descricao', models.TextField(max_length=1536)),
                ('genero', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_nascimento', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vacinas_anuncios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vacina', models.DateField()),
                ('data_vencimento', models.DateField(null=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.anuncio')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vacina')),
            ],
        ),
    ]
