# Generated by Django 4.2.4 on 2023-10-11 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_anuncio_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacinas_anuncios',
            name='vacina',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='vacinas', to='core.vacina'),
        ),
    ]
