# Generated by Django 4.2.4 on 2023-10-11 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_vacinas_anuncios_vacina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacinas_anuncios',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacinas', to='core.anuncio'),
        ),
        migrations.AlterField(
            model_name='vacinas_anuncios',
            name='vacina',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.vacina'),
        ),
    ]
